[build-system]
requires = ["setuptools>=61", "wheel>=0.36"]
build-backend = "setuptools.build_meta"

[project]
version = "1.0.0"
name = "mazegen"
description = "A-Maze-ing"
requires-python = ">=3.11"
dependencies = ["numpy>=2.1.0"]

[tool.setuptools]
packages = ["mazegen"]
package-dir = { "mazegen" = "." }
